// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for store.categories */
export type CategoriesId = string & { __brand: 'CategoriesId' };

/** Represents the table store.categories */
export default interface Categories {
  id: CategoriesId;

  name: string;
}

/** Represents the initializer for the table store.categories */
export interface CategoriesInitializer {
  /** Default value: nextval('store.categories_id_seq'::regclass) */
  id?: CategoriesId;

  name: string;
}

/** Represents the mutator for the table store.categories */
export interface CategoriesMutator {
  id?: CategoriesId;

  name?: string;
}
