// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for store.products */
export type ProductsId = string & { __brand: 'ProductsId' };

/** Represents the table store.products */
export default interface Products {
  id: ProductsId;

  title: string;

  description: string;

  price: number;
}

/** Represents the initializer for the table store.products */
export interface ProductsInitializer {
  /** Default value: nextval('store.products_id_seq'::regclass) */
  id?: ProductsId;

  title: string;

  description: string;

  price: number;
}

/** Represents the mutator for the table store.products */
export interface ProductsMutator {
  id?: ProductsId;

  title?: string;

  description?: string;

  price?: number;
}
