// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for users.users */
export type UsersId = string & { __brand: 'UsersId' };

/** Represents the table users.users */
export default interface Users {
  id: UsersId;

  display_name: string;

  email_address: string;

  hashed_password: Buffer;

  salt: Buffer;
}

/** Represents the initializer for the table users.users */
export interface UsersInitializer {
  /** Default value: nextval('users.users_id_seq'::regclass) */
  id?: UsersId;

  display_name: string;

  email_address: string;

  hashed_password: Buffer;

  salt: Buffer;
}

/** Represents the mutator for the table users.users */
export interface UsersMutator {
  id?: UsersId;

  display_name?: string;

  email_address?: string;

  hashed_password?: Buffer;

  salt?: Buffer;
}
